version: '3.5'
services:
  app:
    container_name: ${PROJECT_NAME}-app
    image: dersonsena/php-nginx-dev
    volumes:
      - ./:/var/www/html
    environment:
      - XDEBUG_START_WITH_REQUEST=yes
      - XDEBUG_DISCOVER_CLIENT_HOST=0
      - XDEBUG_MODE=coverage,develop,debug
      - NGINX_DOCUMENT_ROOT=/var/www/html/public
      - PHP_MAX_EXECUTION_TIME=90
    ports:
      - '${DOCKER_APP_PORT}:80'
      - '${DOCKER_APP_PORT_SSL}:443'
    networks:
      - gettobi-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: ${PROJECT_NAME}-db
    command: --default-authentication-plugin=mysql_native_password --explicit_defaults_for_timestamp=1
    restart: always
    ports:
      - "${DOCKER_MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    networks:
      - gettobi-network
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql

networks:
  gettobi-network:
    driver: bridge
