<?php
/**
 * This class has been auto-generated by PHP-DI.
 */
class CompiledContainer extends DI\CompiledContainer{
    const METHOD_MAPPING = array (
  'Odan\\Session\\SessionInterface' => 'get1',
  'Odan\\Session\\Middleware\\SessionMiddleware' => 'get2',
  'Slim\\Flash\\Messages' => 'get3',
  'settings' => 'get4',
  'subEntry1' => 'get5',
);

    protected function get1()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
            $sessionParams = $c->get('settings')['session'];
            $session = new \Odan\Session\PhpSession();
            $session->setOptions($sessionParams);
            return $session;
        }, 'Odan\\Session\\SessionInterface');
    }

    protected function get2()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
            return new \Odan\Session\Middleware\SessionMiddleware($c->get(\Odan\Session\SessionInterface::class));
        }, 'Odan\\Session\\Middleware\\SessionMiddleware');
    }

    protected function get3()
    {
        return $this->resolveFactory(static function (\Psr\Container\ContainerInterface $c) {
            $storage = [];
            return new \Slim\Flash\Messages($storage);
        }, 'Slim\\Flash\\Messages');
    }

    protected function get5()
    {
        return [
            'cache_expire' => 0,
            'cookie_httponly' => true,
            'cookie_secure' => false,
        ];
    }

    protected function get4()
    {
        return [
            'displayErrorDetails' => true,
            'session' => $this->get5(),
        ];
    }

}
